package persitence.db.model;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * BioMeasure generated by hbm2java
 */
@Entity
@Table(name="bio_measure"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class BioMeasure  implements java.io.Serializable {


    // Fields    

     private String codMeasure;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private int optimistLock;
     private String formula;
     private String name;
     private String description;


    // Constructors

    /** default constructor */
    public BioMeasure() {
    }

	/** minimal constructor */
    public BioMeasure(String codMeasure, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String formula) {
        this.codMeasure = codMeasure;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.formula = formula;
    }
    
    /** full constructor */
    public BioMeasure(String codMeasure, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String formula, String name, String description) {
        this.codMeasure = codMeasure;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.formula = formula;
        this.name = name;
        this.description = description;
    }
    

   
    // Property accessors
    @Id
    @Column(name="COD_MEASURE", unique=true, nullable=false, insertable=true, updatable=true, length=10)

    public String getCodMeasure() {
        return this.codMeasure;
    }
    
    public void setCodMeasure(String codMeasure) {
        this.codMeasure = codMeasure;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=50)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true)

    public int getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(int optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="FORMULA", unique=false, nullable=false, insertable=true, updatable=true, length=500)

    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }
    @Column(name="NAME", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=500)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}
