package persitence.db.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * ExerciseRutine generated by hbm2java
 */
@Entity
@Table(name="exercise_rutine"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class ExerciseRutine  implements java.io.Serializable {


    // Fields    

     private int idExerciseRutine;
     private Rutine rutine;
     private ExerciseMeasure exerciseMeasure;
     private Exercise exercise;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private int optimistLock;
     private int seriesNumber;
     private int duration;
     private int exerciseOrder;
     private BigDecimal weight;
     private Set exerciseRutineHistorics = new HashSet(0);


    // Constructors

    /** default constructor */
    public ExerciseRutine() {
    }

	/** minimal constructor */
    public ExerciseRutine(int idExerciseRutine, Rutine rutine, ExerciseMeasure exerciseMeasure, Exercise exercise, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, int seriesNumber, int duration, int exerciseOrder) {
        this.idExerciseRutine = idExerciseRutine;
        this.rutine = rutine;
        this.exerciseMeasure = exerciseMeasure;
        this.exercise = exercise;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.seriesNumber = seriesNumber;
        this.duration = duration;
        this.exerciseOrder = exerciseOrder;
    }
    
    /** full constructor */
    public ExerciseRutine(int idExerciseRutine, Rutine rutine, ExerciseMeasure exerciseMeasure, Exercise exercise, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, int seriesNumber, int duration, int exerciseOrder, BigDecimal weight, Set exerciseRutineHistorics) {
        this.idExerciseRutine = idExerciseRutine;
        this.rutine = rutine;
        this.exerciseMeasure = exerciseMeasure;
        this.exercise = exercise;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.seriesNumber = seriesNumber;
        this.duration = duration;
        this.exerciseOrder = exerciseOrder;
        this.weight = weight;
        this.exerciseRutineHistorics = exerciseRutineHistorics;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_EXERCISE_RUTINE", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdExerciseRutine() {
        return this.idExerciseRutine;
    }
    
    public void setIdExerciseRutine(int idExerciseRutine) {
        this.idExerciseRutine = idExerciseRutine;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="ID_RUTINE", unique=false, nullable=false, insertable=true, updatable=true)

    public Rutine getRutine() {
        return this.rutine;
    }
    
    public void setRutine(Rutine rutine) {
        this.rutine = rutine;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_EXERCISE_MEASURE_TYPE", unique=false, nullable=false, insertable=true, updatable=true)

    public ExerciseMeasure getExerciseMeasure() {
        return this.exerciseMeasure;
    }
    
    public void setExerciseMeasure(ExerciseMeasure exerciseMeasure) {
        this.exerciseMeasure = exerciseMeasure;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="ID_EXERCISE", unique=false, nullable=false, insertable=true, updatable=true)

    public Exercise getExercise() {
        return this.exercise;
    }
    
    public void setExercise(Exercise exercise) {
        this.exercise = exercise;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true)

    public int getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(int optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="SERIES_NUMBER", unique=false, nullable=false, insertable=true, updatable=true)

    public int getSeriesNumber() {
        return this.seriesNumber;
    }
    
    public void setSeriesNumber(int seriesNumber) {
        this.seriesNumber = seriesNumber;
    }
    @Column(name="DURATION", unique=false, nullable=false, insertable=true, updatable=true)

    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    @Column(name="EXERCISE_ORDER", unique=false, nullable=false, insertable=true, updatable=true)

    public int getExerciseOrder() {
        return this.exerciseOrder;
    }
    
    public void setExerciseOrder(int exerciseOrder) {
        this.exerciseOrder = exerciseOrder;
    }
    @Column(name="WEIGHT", unique=false, nullable=true, insertable=true, updatable=true, precision=10)

    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="exerciseRutine")

    public Set getExerciseRutineHistorics() {
        return this.exerciseRutineHistorics;
    }
    
    public void setExerciseRutineHistorics(Set exerciseRutineHistorics) {
        this.exerciseRutineHistorics = exerciseRutineHistorics;
    }
   








}
