package persitence.db.model;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exercise generated by hbm2java.
 */
@Entity
@Table(name = "exercise", catalog = "personalTrainer", uniqueConstraints = {})

public class Exercise extends AuditableEntity implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -432981352681456006L;

	/** The id exercise. */
	@Id
	@Column(name = "ID_EXERCISE")
	private Integer idExercise;

	/** The exercise type. */
	@ManyToOne()
	@JoinColumn(name = "COD_EXERCISE_TYPE")
	private ExerciseType exerciseType;

	/** The name. */
	@Column(name = "NAME", length = 50)
	private String name;

	/** The description. */
	@Column(name = "DESCRIPTION", length = 100)
	private String description;

	/** The url demo. */
	@Column(name = "URL_DEMO", length = 500)
	private String urlDemo;

	/** The exercise muscles. */
	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "exercise")
	private Set<ExerciseMuscle> exerciseMuscles = new HashSet<>(0);

	/** The exercise rutine historics. */
	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "exercise")
	private Set<ExerciseRutineHistoric> exerciseRutineHistorics = new HashSet<>(0);

	/** The exercise rutines. */
	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "exercise")
	private Set<ExerciseRutine> exerciseRutines = new HashSet<>(0);

	/**
	 * Gets the id exercise.
	 *
	 * @return the id exercise
	 */
	// Property accessors

	public Integer getIdExercise() {
		return idExercise;
	}

	/**
	 * Sets the id exercise.
	 *
	 * @param idExercise
	 *            the new id exercise
	 */
	public void setIdExercise(final Integer idExercise) {
		this.idExercise = idExercise;
	}

	/**
	 * Gets the exercise type.
	 *
	 * @return the exercise type
	 */

	public ExerciseType getExerciseType() {
		return exerciseType;
	}

	/**
	 * Sets the exercise type.
	 *
	 * @param exerciseType
	 *            the new exercise type
	 */
	public void setExerciseType(final ExerciseType exerciseType) {
		this.exerciseType = exerciseType;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */

	public String getName() {
		return name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name
	 *            the new name
	 */
	public void setName(final String name) {
		this.name = name;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */

	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description
	 *            the new description
	 */
	public void setDescription(final String description) {
		this.description = description;
	}

	/**
	 * Gets the url demo.
	 *
	 * @return the url demo
	 */

	public String getUrlDemo() {
		return urlDemo;
	}

	/**
	 * Sets the url demo.
	 *
	 * @param urlDemo
	 *            the new url demo
	 */
	public void setUrlDemo(final String urlDemo) {
		this.urlDemo = urlDemo;
	}

	/**
	 * Gets the exercise muscles.
	 *
	 * @return the exercise muscles
	 */

	public Set<ExerciseMuscle> getExerciseMuscles() {
		return exerciseMuscles;
	}

	/**
	 * Sets the exercise muscles.
	 *
	 * @param exerciseMuscles
	 *            the new exercise muscles
	 */
	public void setExerciseMuscles(final Set<ExerciseMuscle> exerciseMuscles) {
		this.exerciseMuscles = exerciseMuscles;
	}

	/**
	 * Gets the exercise rutine historics.
	 *
	 * @return the exercise rutine historics
	 */

	public Set<ExerciseRutineHistoric> getExerciseRutineHistorics() {
		return exerciseRutineHistorics;
	}

	/**
	 * Sets the exercise rutine historics.
	 *
	 * @param exerciseRutineHistorics
	 *            the new exercise rutine historics
	 */
	public void setExerciseRutineHistorics(final Set<ExerciseRutineHistoric> exerciseRutineHistorics) {
		this.exerciseRutineHistorics = exerciseRutineHistorics;
	}

	/**
	 * Gets the exercise rutines.
	 *
	 * @return the exercise rutines
	 */

	public Set<ExerciseRutine> getExerciseRutines() {
		return exerciseRutines;
	}

	/**
	 * Sets the exercise rutines.
	 *
	 * @param exerciseRutines
	 *            the new exercise rutines
	 */
	public void setExerciseRutines(final Set<ExerciseRutine> exerciseRutines) {
		this.exerciseRutines = exerciseRutines;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {

		return Objects.hash(idExercise);
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		if (null == idExercise || null == ((Exercise) obj).getIdExercise()) {
			return false;
		}
		return Objects.equals(idExercise, ((Exercise) obj).getIdExercise());
	}
}
