package persitence.db.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * ExerciseType generated by hbm2java
 */
@Entity
@Table(name="exercise_type"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class ExerciseType  implements java.io.Serializable {


    // Fields    

     private String codExerciseType;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private int optimistLock;
     private String nameType;
     private String description;
     private Set exercises = new HashSet(0);


    // Constructors

    /** default constructor */
    public ExerciseType() {
    }

	/** minimal constructor */
    public ExerciseType(String codExerciseType, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String nameType) {
        this.codExerciseType = codExerciseType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.nameType = nameType;
    }
    
    /** full constructor */
    public ExerciseType(String codExerciseType, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String nameType, String description, Set exercises) {
        this.codExerciseType = codExerciseType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.nameType = nameType;
        this.description = description;
        this.exercises = exercises;
    }
    

   
    // Property accessors
    @Id
    @Column(name="COD_EXERCISE_TYPE", unique=true, nullable=false, insertable=true, updatable=true, length=10)

    public String getCodExerciseType() {
        return this.codExerciseType;
    }
    
    public void setCodExerciseType(String codExerciseType) {
        this.codExerciseType = codExerciseType;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true)

    public int getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(int optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="NAME_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getNameType() {
        return this.nameType;
    }
    
    public void setNameType(String nameType) {
        this.nameType = nameType;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="exerciseType")

    public Set getExercises() {
        return this.exercises;
    }
    
    public void setExercises(Set exercises) {
        this.exercises = exercises;
    }
   








}
