package persitence.db.model;
// Generated 08-sep-2013 9:45:08 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExerciseMeasure generated by hbm2java.
 */
@Entity
@Table(name = "exercise_measure", catalog = "personalTrainer", uniqueConstraints = {})

public class ExerciseMeasureJPA extends AuditableEntityJPA implements java.io.Serializable {

	// Fields

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 2700850321566849630L;

	/** The cod exercise measure type. */
	@Id
	@Column(name = "COD_EXERCISE_MEASURE_TYPE", length = 10)
	private String codExerciseMeasureType;

	/** The name type. */
	@Column(name = "NAME_TYPE", length = 50)
	private String nameType;

	/** The description. */
	@Column(name = "DESCRIPTION", length = 100)
	private String description;

	/** The exercise rutine historics. */
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "exerciseMeasure")
	private Set<ExerciseRutineHistoricJPA> exerciseRutineHistorics = new HashSet<>(0);

	/** The exercise rutines. */
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "exerciseMeasure")

	private Set<ExerciseRutineJPA> exerciseRutines = new HashSet<>(0);

	// Property accessors

	/**
	 * Gets the cod exercise measure type.
	 *
	 * @return the cod exercise measure type
	 */
	public String getCodExerciseMeasureType() {
		return codExerciseMeasureType;
	}

	/**
	 * Sets the cod exercise measure type.
	 *
	 * @param codExerciseMeasureType
	 *            the new cod exercise measure type
	 */
	public void setCodExerciseMeasureType(final String codExerciseMeasureType) {
		this.codExerciseMeasureType = codExerciseMeasureType;
	}

	/**
	 * Gets the name type.
	 *
	 * @return the name type
	 */
	public String getNameType() {
		return nameType;
	}

	/**
	 * Sets the name type.
	 *
	 * @param nameType
	 *            the new name type
	 */
	public void setNameType(final String nameType) {
		this.nameType = nameType;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description
	 *            the new description
	 */
	public void setDescription(final String description) {
		this.description = description;
	}

	/**
	 * Gets the exercise rutine historics.
	 *
	 * @return the exercise rutine historics
	 */
	public Set<ExerciseRutineHistoricJPA> getExerciseRutineHistorics() {
		return exerciseRutineHistorics;
	}

	/**
	 * Sets the exercise rutine historics.
	 *
	 * @param exerciseRutineHistorics
	 *            the new exercise rutine historics
	 */
	public void setExerciseRutineHistorics(final Set<ExerciseRutineHistoricJPA> exerciseRutineHistorics) {
		this.exerciseRutineHistorics = exerciseRutineHistorics;
	}

	/**
	 * Gets the exercise rutines.
	 *
	 * @return the exercise rutines
	 */
	public Set<ExerciseRutineJPA> getExerciseRutines() {
		return exerciseRutines;
	}

	/**
	 * Sets the exercise rutines.
	 *
	 * @param exerciseRutines
	 *            the new exercise rutines
	 */
	public void setExerciseRutines(final Set<ExerciseRutineJPA> exerciseRutines) {
		this.exerciseRutines = exerciseRutines;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {

		return Objects.hash(codExerciseMeasureType);
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		if (null == codExerciseMeasureType || null == ((ExerciseMeasureJPA) obj).getCodExerciseMeasureType()) {
			return false;
		}
		return Objects.equals(codExerciseMeasureType, ((ExerciseMeasureJPA) obj).getCodExerciseMeasureType());
	}
}
