package persitence.db.model;
// Generated 08-sep-2013 9:45:08 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Exercise generated by hbm2java
 */
@Entity
@Table(name="exercise"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class Exercise  implements java.io.Serializable {


    // Fields    

     private int idExercise;
     private ExerciseType exerciseType;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private int optimistLock;
     private String name;
     private String description;
     private String urlDemo;
     private Set exerciseMuscles = new HashSet(0);
     private Set exerciseRutineHistorics = new HashSet(0);
     private Set exerciseRutines = new HashSet(0);


    // Constructors

    /** default constructor */
    public Exercise() {
    }

	/** minimal constructor */
    public Exercise(int idExercise, ExerciseType exerciseType, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String name) {
        this.idExercise = idExercise;
        this.exerciseType = exerciseType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.name = name;
    }
    
    /** full constructor */
    public Exercise(int idExercise, ExerciseType exerciseType, Date createDate, Date updateDate, String updateUser, String updateProgram, int optimistLock, String name, String description, String urlDemo, Set exerciseMuscles, Set exerciseRutineHistorics, Set exerciseRutines) {
        this.idExercise = idExercise;
        this.exerciseType = exerciseType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.name = name;
        this.description = description;
        this.urlDemo = urlDemo;
        this.exerciseMuscles = exerciseMuscles;
        this.exerciseRutineHistorics = exerciseRutineHistorics;
        this.exerciseRutines = exerciseRutines;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_EXERCISE", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdExercise() {
        return this.idExercise;
    }
    
    public void setIdExercise(int idExercise) {
        this.idExercise = idExercise;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="COD_EXERCISE_TYPE", unique=false, nullable=false, insertable=true, updatable=true)

    public ExerciseType getExerciseType() {
        return this.exerciseType;
    }
    
    public void setExerciseType(ExerciseType exerciseType) {
        this.exerciseType = exerciseType;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true)

    public int getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(int optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="NAME", unique=false, nullable=false, insertable=true, updatable=true, length=50)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="URL_DEMO", unique=false, nullable=true, insertable=true, updatable=true, length=500)

    public String getUrlDemo() {
        return this.urlDemo;
    }
    
    public void setUrlDemo(String urlDemo) {
        this.urlDemo = urlDemo;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="exercise")

    public Set getExerciseMuscles() {
        return this.exerciseMuscles;
    }
    
    public void setExerciseMuscles(Set exerciseMuscles) {
        this.exerciseMuscles = exerciseMuscles;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="exercise")

    public Set getExerciseRutineHistorics() {
        return this.exerciseRutineHistorics;
    }
    
    public void setExerciseRutineHistorics(Set exerciseRutineHistorics) {
        this.exerciseRutineHistorics = exerciseRutineHistorics;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="exercise")

    public Set getExerciseRutines() {
        return this.exerciseRutines;
    }
    
    public void setExerciseRutines(Set exerciseRutines) {
        this.exerciseRutines = exerciseRutines;
    }
   








}
