package persitence.db.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExerciseRutine generated by hbm2java.
 */
@Entity
@Table(name = "exercise_rutine", catalog = "personalTrainer", uniqueConstraints = {})

public class ExerciseRutine extends AuditableEntity implements java.io.Serializable {

	// Fields

	/** The id exercise rutine. */
	@Id
	@Column(name = "ID_EXERCISE_RUTINE", unique = true, nullable = false, insertable = true, updatable = true)
	private Integer idExerciseRutine;

	/** The rutine. */
	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RUTINE", unique = false, nullable = false, insertable = true, updatable = true)
	private Rutine rutine;

	/** The exercise measure. */
	@ManyToOne()
	@JoinColumn(name = "COD_EXERCISE_MEASURE_TYPE")
	private ExerciseMeasure exerciseMeasure;

	/** The exercise. */
	@ManyToOne()
	@JoinColumn(name = "ID_EXERCISE")
	private Exercise exercise;

	/** The series number. */
	@Column(name = "SERIES_NUMBER")
	private Integer seriesNumber;

	/** The duration. */
	@Column(name = "DURATION")
	private Integer duration;

	/** The exercise order. */
	@Column(name = "EXERCISE_ORDER", unique = false, nullable = false, insertable = true, updatable = true)
	private Integer exerciseOrder;

	/** The weight. */
	@Column(name = "WEIGHT", unique = false, nullable = true, insertable = true, updatable = true, precision = 10)
	private BigDecimal weight;

	/** The exercise rutine historics. */
	@OneToMany(cascade = { CascadeType.ALL }, mappedBy = "exerciseRutine")
	private Set<ExerciseRutineHistoric> exerciseRutineHistorics = new HashSet<>(0);

	/**
	 * Gets the id exercise rutine.
	 *
	 * @return the id exercise rutine
	 */
	public Integer getIdExerciseRutine() {
		return idExerciseRutine;
	}

	/**
	 * Sets the id exercise rutine.
	 *
	 * @param idExerciseRutine
	 *            the new id exercise rutine
	 */
	public void setIdExerciseRutine(final Integer idExerciseRutine) {
		this.idExerciseRutine = idExerciseRutine;
	}

	/**
	 * Gets the rutine.
	 *
	 * @return the rutine
	 */
	public Rutine getRutine() {
		return rutine;
	}

	/**
	 * Sets the rutine.
	 *
	 * @param rutine
	 *            the new rutine
	 */
	public void setRutine(final Rutine rutine) {
		this.rutine = rutine;
	}

	/**
	 * Gets the exercise measure.
	 *
	 * @return the exercise measure
	 */
	public ExerciseMeasure getExerciseMeasure() {
		return exerciseMeasure;
	}

	/**
	 * Sets the exercise measure.
	 *
	 * @param exerciseMeasure
	 *            the new exercise measure
	 */
	public void setExerciseMeasure(final ExerciseMeasure exerciseMeasure) {
		this.exerciseMeasure = exerciseMeasure;
	}

	/**
	 * Gets the exercise.
	 *
	 * @return the exercise
	 */
	public Exercise getExercise() {
		return exercise;
	}

	/**
	 * Sets the exercise.
	 *
	 * @param exercise
	 *            the new exercise
	 */
	public void setExercise(final Exercise exercise) {
		this.exercise = exercise;
	}

	/**
	 * Gets the series number.
	 *
	 * @return the series number
	 */
	public Integer getSeriesNumber() {
		return seriesNumber;
	}

	/**
	 * Sets the series number.
	 *
	 * @param seriesNumber
	 *            the new series number
	 */
	public void setSeriesNumber(final Integer seriesNumber) {
		this.seriesNumber = seriesNumber;
	}

	/**
	 * Gets the duration.
	 *
	 * @return the duration
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * Sets the duration.
	 *
	 * @param duration
	 *            the new duration
	 */
	public void setDuration(final Integer duration) {
		this.duration = duration;
	}

	/**
	 * Gets the exercise order.
	 *
	 * @return the exercise order
	 */
	public Integer getExerciseOrder() {
		return exerciseOrder;
	}

	/**
	 * Sets the exercise order.
	 *
	 * @param exerciseOrder
	 *            the new exercise order
	 */
	public void setExerciseOrder(final Integer exerciseOrder) {
		this.exerciseOrder = exerciseOrder;
	}

	/**
	 * Gets the weight.
	 *
	 * @return the weight
	 */
	public BigDecimal getWeight() {
		return weight;
	}

	/**
	 * Sets the weight.
	 *
	 * @param weight
	 *            the new weight
	 */
	public void setWeight(final BigDecimal weight) {
		this.weight = weight;
	}

	/**
	 * Gets the exercise rutine historics.
	 *
	 * @return the exercise rutine historics
	 */
	public Set<ExerciseRutineHistoric> getExerciseRutineHistorics() {
		return exerciseRutineHistorics;
	}

	/**
	 * Sets the exercise rutine historics.
	 *
	 * @param exerciseRutineHistorics
	 *            the new exercise rutine historics
	 */
	public void setExerciseRutineHistorics(final Set<ExerciseRutineHistoric> exerciseRutineHistorics) {
		this.exerciseRutineHistorics = exerciseRutineHistorics;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {

		return Objects.hash(idExerciseRutine);
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object obj) {
		if (null == idExerciseRutine || null == ((ExerciseRutine) obj).getIdExerciseRutine()) {
			return false;
		}
		return Objects.equals(idExerciseRutine, ((ExerciseRutine) obj).getIdExerciseRutine());
	}
}
