package persitence.db.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Muscle generated by hbm2java
 */
@Entity
@Table(name = "muscle", catalog = "personalTrainer", uniqueConstraints = {})

public class MuscleJPA {

	// Fields

	private int idMuscle;
	private Date createDate;
	private Date updateDate;
	private String updateUser;
	private String updateProgram;
	private int optimistLock;
	private String name;
	private Set exerciseMuscles = new HashSet(0);

	// Constructors

	/** default constructor */
	public MuscleJPA() {
	}

	/** minimal constructor */
	public MuscleJPA(final int idMuscle, final Date createDate, final Date updateDate, final String updateUser,
			final String updateProgram, final int optimistLock, final String name) {
		this.idMuscle = idMuscle;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.updateProgram = updateProgram;
		this.optimistLock = optimistLock;
		this.name = name;
	}

	/** full constructor */
	public MuscleJPA(final int idMuscle, final Date createDate, final Date updateDate, final String updateUser,
			final String updateProgram, final int optimistLock, final String name, final Set exerciseMuscles) {
		this.idMuscle = idMuscle;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.updateProgram = updateProgram;
		this.optimistLock = optimistLock;
		this.name = name;
		this.exerciseMuscles = exerciseMuscles;
	}

	// Property accessors
	@Id
	@Column(name = "ID_MUSCLE", unique = true, nullable = false, insertable = true, updatable = true)

	public int getIdMuscle() {
		return idMuscle;
	}

	public void setIdMuscle(final int idMuscle) {
		this.idMuscle = idMuscle;
	}

	@Column(name = "CREATE_DATE", unique = false, nullable = false, insertable = true, updatable = true, length = 19)

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(final Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_DATE", unique = false, nullable = false, insertable = true, updatable = true, length = 19)

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(final Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_USER", unique = false, nullable = false, insertable = true, updatable = true, length = 10)

	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(final String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "UPDATE_PROGRAM", unique = false, nullable = false, insertable = true, updatable = true, length = 45)

	public String getUpdateProgram() {
		return updateProgram;
	}

	public void setUpdateProgram(final String updateProgram) {
		this.updateProgram = updateProgram;
	}

	@Column(name = "OPTIMIST_LOCK", unique = false, nullable = false, insertable = true, updatable = true)

	public int getOptimistLock() {
		return optimistLock;
	}

	public void setOptimistLock(final int optimistLock) {
		this.optimistLock = optimistLock;
	}

	@Column(name = "NAME", unique = false, nullable = false, insertable = true, updatable = true, length = 100)

	public String getName() {
		return name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "muscle")

	public Set getExerciseMuscles() {
		return exerciseMuscles;
	}

	public void setExerciseMuscles(final Set exerciseMuscles) {
		this.exerciseMuscles = exerciseMuscles;
	}

}
