package persitence.db.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * UserData generated by hbm2java
 */
@Entity
@Table(name="user_data"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class UserData  implements java.io.Serializable {


    // Fields    

     private int idUserData;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private short optimistLock;
     private String sex;
     private BigDecimal weight;
     private BigDecimal height;
     private BigDecimal belly;
     private BigDecimal hip;
     private BigDecimal chest;
     private String mail;
     private String name;
     private BigDecimal imc;
     private BigDecimal igc;
     private BigDecimal mcm;
     private BigDecimal mb;
     private BigDecimal baseHeartRate;
     private BigDecimal bellyHeightRate;
     private String age;
     private BigDecimal maxHeartRate;
     private String heartRatea;
     private String heartRateb;
     private String heartRatec;
     private String heartRated;
     private String heartRatee;
     private Set rutines = new HashSet(0);
     private Set userDataHistorics = new HashSet(0);


    // Constructors

    /** default constructor */
    public UserData() {
    }

	

   
    // Property accessors
    @Id
    @Column(name="ID_USER_DATA", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdUserData() {
        return this.idUserData;
    }
    
    public void setIdUserData(int idUserData) {
        this.idUserData = idUserData;
    }
    
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="SEX", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    @Column(name="WEIGHT", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    @Column(name="HEIGHT", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }
    @Column(name="BELLY", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBelly() {
        return this.belly;
    }
    
    public void setBelly(BigDecimal belly) {
        this.belly = belly;
    }
    @Column(name="HIP", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getHip() {
        return this.hip;
    }
    
    public void setHip(BigDecimal hip) {
        this.hip = hip;
    }
    @Column(name="CHEST", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getChest() {
        return this.chest;
    }
    
    public void setChest(BigDecimal chest) {
        this.chest = chest;
    }
    @Column(name="MAIL", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    @Column(name="NAME", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="IMC", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getImc() {
        return this.imc;
    }
    
    public void setImc(BigDecimal imc) {
        this.imc = imc;
    }
    @Column(name="IGC", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getIgc() {
        return this.igc;
    }
    
    public void setIgc(BigDecimal igc) {
        this.igc = igc;
    }
    @Column(name="MCM", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMcm() {
        return this.mcm;
    }
    
    public void setMcm(BigDecimal mcm) {
        this.mcm = mcm;
    }
    @Column(name="MB", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMb() {
        return this.mb;
    }
    
    public void setMb(BigDecimal mb) {
        this.mb = mb;
    }
    @Column(name="BASE_HEART_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBaseHeartRate() {
        return this.baseHeartRate;
    }
    
    public void setBaseHeartRate(BigDecimal baseHeartRate) {
        this.baseHeartRate = baseHeartRate;
    }
    @Column(name="BELLY_HEIGHT_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBellyHeightRate() {
        return this.bellyHeightRate;
    }
    
    public void setBellyHeightRate(BigDecimal bellyHeightRate) {
        this.bellyHeightRate = bellyHeightRate;
    }
    @Column(name="AGE", unique=false, nullable=true, insertable=true, updatable=true, length=3)

    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    @Column(name="MAX_HEART_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMaxHeartRate() {
        return this.maxHeartRate;
    }
    
    public void setMaxHeartRate(BigDecimal maxHeartRate) {
        this.maxHeartRate = maxHeartRate;
    }
    @Column(name="HEART_RATEA", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatea() {
        return this.heartRatea;
    }
    
    public void setHeartRatea(String heartRatea) {
        this.heartRatea = heartRatea;
    }
    @Column(name="HEART_RATEB", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRateb() {
        return this.heartRateb;
    }
    
    public void setHeartRateb(String heartRateb) {
        this.heartRateb = heartRateb;
    }
    @Column(name="HEART_RATEC", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatec() {
        return this.heartRatec;
    }
    
    public void setHeartRatec(String heartRatec) {
        this.heartRatec = heartRatec;
    }
    @Column(name="HEART_RATED", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRated() {
        return this.heartRated;
    }
    
    public void setHeartRated(String heartRated) {
        this.heartRated = heartRated;
    }
    @Column(name="HEART_RATEE", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatee() {
        return this.heartRatee;
    }
    
    public void setHeartRatee(String heartRatee) {
        this.heartRatee = heartRatee;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="userData")

    public Set getRutines() {
        return this.rutines;
    }
    
    public void setRutines(Set rutines) {
        this.rutines = rutines;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="userData")

    public Set getUserDataHistorics() {
        return this.userDataHistorics;
    }
    
    public void setUserDataHistorics(Set userDataHistorics) {
        this.userDataHistorics = userDataHistorics;
    }
   








}
