package persitence.db.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * UserDataHistoric generated by hbm2java
 */
@Entity
@Table(name="user_data_historic"
    ,catalog="personalTrainer"
, uniqueConstraints = {  }
)

public class UserDataHistoric  implements java.io.Serializable {


    // Fields    

     private int idUserDataHistoric;
     private UserData userData;
     private Date createDate;
     private Date updateDate;
     private String updateUser;
     private String updateProgram;
     private short optimistLock;
     private BigDecimal weight;
     private BigDecimal height;
     private BigDecimal belly;
     private BigDecimal hip;
     private BigDecimal chest;
     private BigDecimal imc;
     private BigDecimal igc;
     private BigDecimal mcm;
     private BigDecimal mb;
     private BigDecimal baseHeartRate;
     private BigDecimal bellyHeightRate;
     private BigDecimal maxHeartRate;
     private String heartRatea;
     private String heartRateb;
     private String heartRatec;
     private String heartRated;
     private String heartRatee;
     private Date historicDate;


    // Constructors

    /** default constructor */
    public UserDataHistoric() {
    }

	/** minimal constructor */
    public UserDataHistoric(int idUserDataHistoric, UserData userData, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock, Date historicDate) {
        this.idUserDataHistoric = idUserDataHistoric;
        this.userData = userData;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.historicDate = historicDate;
    }
    
    /** full constructor */
    public UserDataHistoric(int idUserDataHistoric, UserData userData, Date createDate, Date updateDate, String updateUser, String updateProgram, short optimistLock, BigDecimal weight, BigDecimal height, BigDecimal belly, BigDecimal hip, BigDecimal chest, BigDecimal imc, BigDecimal igc, BigDecimal mcm, BigDecimal mb, BigDecimal baseHeartRate, BigDecimal bellyHeightRate, BigDecimal maxHeartRate, String heartRatea, String heartRateb, String heartRatec, String heartRated, String heartRatee, Date historicDate) {
        this.idUserDataHistoric = idUserDataHistoric;
        this.userData = userData;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
        this.updateProgram = updateProgram;
        this.optimistLock = optimistLock;
        this.weight = weight;
        this.height = height;
        this.belly = belly;
        this.hip = hip;
        this.chest = chest;
        this.imc = imc;
        this.igc = igc;
        this.mcm = mcm;
        this.mb = mb;
        this.baseHeartRate = baseHeartRate;
        this.bellyHeightRate = bellyHeightRate;
        this.maxHeartRate = maxHeartRate;
        this.heartRatea = heartRatea;
        this.heartRateb = heartRateb;
        this.heartRatec = heartRatec;
        this.heartRated = heartRated;
        this.heartRatee = heartRatee;
        this.historicDate = historicDate;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID_USER_DATA_HISTORIC", unique=true, nullable=false, insertable=true, updatable=true)

    public int getIdUserDataHistoric() {
        return this.idUserDataHistoric;
    }
    
    public void setIdUserDataHistoric(int idUserDataHistoric) {
        this.idUserDataHistoric = idUserDataHistoric;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="ID_USER_DATA", unique=false, nullable=false, insertable=true, updatable=true)

    public UserData getUserData() {
        return this.userData;
    }
    
    public void setUserData(UserData userData) {
        this.userData = userData;
    }
    @Column(name="CREATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Column(name="UPDATE_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    @Column(name="UPDATE_USER", unique=false, nullable=false, insertable=true, updatable=true, length=10)

    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Column(name="UPDATE_PROGRAM", unique=false, nullable=false, insertable=true, updatable=true, length=100)

    public String getUpdateProgram() {
        return this.updateProgram;
    }
    
    public void setUpdateProgram(String updateProgram) {
        this.updateProgram = updateProgram;
    }
    @Column(name="OPTIMIST_LOCK", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

    public short getOptimistLock() {
        return this.optimistLock;
    }
    
    public void setOptimistLock(short optimistLock) {
        this.optimistLock = optimistLock;
    }
    @Column(name="WEIGHT", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    @Column(name="HEIGHT", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }
    @Column(name="BELLY", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBelly() {
        return this.belly;
    }
    
    public void setBelly(BigDecimal belly) {
        this.belly = belly;
    }
    @Column(name="HIP", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getHip() {
        return this.hip;
    }
    
    public void setHip(BigDecimal hip) {
        this.hip = hip;
    }
    @Column(name="CHEST", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getChest() {
        return this.chest;
    }
    
    public void setChest(BigDecimal chest) {
        this.chest = chest;
    }
    @Column(name="IMC", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getImc() {
        return this.imc;
    }
    
    public void setImc(BigDecimal imc) {
        this.imc = imc;
    }
    @Column(name="IGC", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getIgc() {
        return this.igc;
    }
    
    public void setIgc(BigDecimal igc) {
        this.igc = igc;
    }
    @Column(name="MCM", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMcm() {
        return this.mcm;
    }
    
    public void setMcm(BigDecimal mcm) {
        this.mcm = mcm;
    }
    @Column(name="MB", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMb() {
        return this.mb;
    }
    
    public void setMb(BigDecimal mb) {
        this.mb = mb;
    }
    @Column(name="BASE_HEART_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBaseHeartRate() {
        return this.baseHeartRate;
    }
    
    public void setBaseHeartRate(BigDecimal baseHeartRate) {
        this.baseHeartRate = baseHeartRate;
    }
    @Column(name="BELLY_HEIGHT_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getBellyHeightRate() {
        return this.bellyHeightRate;
    }
    
    public void setBellyHeightRate(BigDecimal bellyHeightRate) {
        this.bellyHeightRate = bellyHeightRate;
    }
    @Column(name="MAX_HEART_RATE", unique=false, nullable=true, insertable=true, updatable=true, precision=7)

    public BigDecimal getMaxHeartRate() {
        return this.maxHeartRate;
    }
    
    public void setMaxHeartRate(BigDecimal maxHeartRate) {
        this.maxHeartRate = maxHeartRate;
    }
    @Column(name="HEART_RATEA", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatea() {
        return this.heartRatea;
    }
    
    public void setHeartRatea(String heartRatea) {
        this.heartRatea = heartRatea;
    }
    @Column(name="HEART_RATEB", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRateb() {
        return this.heartRateb;
    }
    
    public void setHeartRateb(String heartRateb) {
        this.heartRateb = heartRateb;
    }
    @Column(name="HEART_RATEC", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatec() {
        return this.heartRatec;
    }
    
    public void setHeartRatec(String heartRatec) {
        this.heartRatec = heartRatec;
    }
    @Column(name="HEART_RATED", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRated() {
        return this.heartRated;
    }
    
    public void setHeartRated(String heartRated) {
        this.heartRated = heartRated;
    }
    @Column(name="HEART_RATEE", unique=false, nullable=true, insertable=true, updatable=true, length=45)

    public String getHeartRatee() {
        return this.heartRatee;
    }
    
    public void setHeartRatee(String heartRatee) {
        this.heartRatee = heartRatee;
    }
    @Column(name="HISTORIC_DATE", unique=false, nullable=false, insertable=true, updatable=true, length=19)

    public Date getHistoricDate() {
        return this.historicDate;
    }
    
    public void setHistoricDate(Date historicDate) {
        this.historicDate = historicDate;
    }
   








}
